### ISSUE TITLE
Automate deployment to s3

### ISSUE THREAD

**Issue by hatchan** [wercker/install-script#1]
Previous wercker.yml deploy section:
```
  installsh:
    - s3sync:
        source-dir: "install_script/"
        bucket-url: $INSTALLSH_BUCKET_URL
        key-id: $AWS_ACCESS_KEY_ID
        key-secret: $AWS_SECRET_ACCESS_KEY
```
